# target_version:
#   rubocop v0.47.1

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - "*.haml"

##################### Bundler ################################
Bundler/OrderedGems:
  Enabled: false

##################### Style ##################################

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces
  Enabled: true

Style/RescueModifier:
  Enabled: false

# EnforcedStyle: require_space =>  2 offenses
# EnforcedStyle: require_no_space => 6 offenses
Style/SpaceInLambdaLiteral:
  # EnforcedStyle: require_space
  Enabled: false

# EnforcedStyle: single_quotes =>  228 offenses
# EnforcedStyle: double_quotes => 3204 offenses
Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

##################### Metrics ################################

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

##################### Lint ###################################

################## Peformance ################################

Performance/RedundantMerge:
  Enabled: false

################## Security ################################
Security/YAMLLoad:
  Enabled: false

############# Below here is generated by gry #################

# EnforcedStyle: outdent => 77 offenses
# EnforcedStyle: indent => 0 offense
Style/AccessModifierIndentation:
  EnforcedStyle: indent
  Enabled: true

# EnforcedStyle: with_first_parameter => 10 offenses
# EnforcedStyle: with_fixed_indentation => 24 offenses
Style/AlignParameters:
  EnforcedStyle: with_first_parameter
  Enabled: true

# EnforcedStyle: is_a? => 2 offenses
# EnforcedStyle: kind_of? => 20 offenses
Style/ClassCheck:
  EnforcedStyle: is_a?
  Enabled: true

# EnforcedStyle: assign_to_condition => 0 offense
# EnforcedStyle: assign_inside_condition => 18 offenses
Style/ConditionalAssignment:
  EnforcedStyle: assign_to_condition
  Enabled: true

# EnforcedStyle: leading => 55 offenses
# EnforcedStyle: trailing => 1 offense
Style/DotPosition:
  EnforcedStyle: trailing
  Enabled: true

# EnforcedStyle: empty_lines => 4827 offenses
# EnforcedStyle: no_empty_lines => 3 offenses
Style/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines
  Enabled: true

# EnforcedStyle: compact => 17 offenses
# EnforcedStyle: expanded => 0 offense
Style/EmptyMethod:
  EnforcedStyle: expanded
  Enabled: true

# EnforcedStyle: for => 60 offenses
# EnforcedStyle: each => 0 offense
Style/For:
  EnforcedStyle: each
  Enabled: true

# EnforcedStyle: format => 20 offenses
# EnforcedStyle: sprintf => 21 offenses
# EnforcedStyle: percent => 1 offense
Style/FormatString:
  EnforcedStyle: percent
  Enabled: true

# EnforcedStyle: when_needed => 882 offenses
# EnforcedStyle: always => 882 offenses
# EnforcedStyle: never => 0 offense
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
  Enabled: true

# EnforcedStyle: ruby19 => 11 offenses
# EnforcedStyle: hash_rockets => 4328 offenses
# EnforcedStyle: no_mixed_keys => 0 offense
# EnforcedStyle: ruby19_no_mixed_keys => 11 offenses
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
  Enabled: true

# EnforcedStyle: line_count_dependent => 0 offense
# EnforcedStyle: lambda => 36 offenses
# EnforcedStyle: literal => 18 offenses
Style/Lambda:
  EnforcedStyle: line_count_dependent
  Enabled: true

# EnforcedStyle: predicate => 17 offenses
# EnforcedStyle: comparison => 0 offense
Style/NumericPredicate:
  EnforcedStyle: comparison
  Enabled: true

# EnforcedStyle: require_parentheses => 0 offense
# EnforcedStyle: require_no_parentheses => 2902 offenses
# EnforcedStyle: require_no_parentheses_except_multiline => 2902 offenses
Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses
  Enabled: true

# EnforcedStyle: snake_case => 2 offenses
# EnforcedStyle: camelCase => 5147 offenses
Style/MethodName:
  EnforcedStyle: snake_case
  Enabled: true

# EnforcedStyle: same_line => 0 offense
# EnforcedStyle: new_line => 39 offenses
Style/MultilineAssignmentLayout:
  EnforcedStyle: same_line
  Enabled: true

# EnforcedStyle: symmetrical => 1 offense
# EnforcedStyle: new_line => 18 offenses
# EnforcedStyle: same_line => 126 offenses
Style/MultilineMethodCallBraceLayout:
  EnforcedStyle: symmetrical
  Enabled: true

# EnforcedStyle: aligned => 1 offense
# EnforcedStyle: indented => 28 offenses
# EnforcedStyle: indented_relative_to_receiver => 28 offenses
Style/MultilineMethodCallIndentation:
  EnforcedStyle: aligned
  Enabled: true

# EnforcedStyle: short => 0 offense
# EnforcedStyle: verbose => 21 offenses
Style/PreferredHashMethods:
  EnforcedStyle: short
  Enabled: true

# EnforcedStyle: compact => 29 offenses
# EnforcedStyle: exploded => 0 offense
Style/RaiseArgs:
  EnforcedStyle: exploded
  Enabled: true

# EnforcedStyle: only_raise => 0 offense
# EnforcedStyle: only_fail => 71 offenses
# EnforcedStyle: semantic => 53 offenses
Style/SignalException:
  EnforcedStyle: only_raise
  Enabled: true

# EnforcedStyle: single_quotes => 0 offense
# EnforcedStyle: double_quotes => 35 offenses
Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
  Enabled: true

# EnforcedStyleInsidePipes: space => 545 offenses
# EnforcedStyleInsidePipes: no_space => 1 offense
Style/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: no_space
  Enabled: true

# EnforcedStyle: space => 3 offenses
# EnforcedStyle: no_space => 70 offenses
Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space
  Enabled: true

# EnforcedStyle: space => 9 offenses
# EnforcedStyle: no_space => 1330 offenses
Style/SpaceBeforeBlockBraces:
  EnforcedStyle: space
  Enabled: true

# EnforcedStyle: space => 380 offenses
# EnforcedStyle: no_space => 0 offense
Style/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space
  Enabled: true

# EnforcedStyle: final_newline => 3 offenses
# EnforcedStyle: final_blank_line => 879 offenses
Style/TrailingBlankLines:
  EnforcedStyle: final_newline
  Enabled: true

# EnforcedStyleForMultiline: comma => 122 offenses
# EnforcedStyleForMultiline: consistent_comma => 144 offenses
# EnforcedStyleForMultiline: no_comma => 0 offense
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma
  Enabled: true

# EnforcedStyleForMultiline: comma => 135 offenses
# EnforcedStyleForMultiline: consistent_comma => 140 offenses
# EnforcedStyleForMultiline: no_comma => 1 offense
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: no_comma
  Enabled: true

# EnforcedStyle: snake_case => 434 offenses
# EnforcedStyle: normalcase => 0 offense
# EnforcedStyle: non_integer => 434 offenses
Style/VariableNumber:
  EnforcedStyle: normalcase
  Enabled: true

# EnforcedStyleAlignWith: keyword => 0 offense
# EnforcedStyleAlignWith: variable => 10 offenses
# EnforcedStyleAlignWith: start_of_line => 10 offenses
Lint/EndAlignment:
  EnforcedStyleAlignWith: keyword
  Enabled: true

# EnforcedStyle: action => 1 offense
# EnforcedStyle: filter => 78 offenses
Rails/ActionFilter:
  EnforcedStyle: action
  Enabled: true
